Feature/add merged config
northwoods/config pull request #12
Opened 2018-01-30 00:43 UTC by kegi

To test this, add an option "merge" = true and request an array (ex: database.connections).

note: Unit test coverage is still 100%

2018-01-30 17:00 UTC, shadowhand requested changes

2018-01-30 17:00 UTC, shadowhand commented on src/ConfigCollection.php
> +    protected $configs;
I'd like to avoid this if at all possible. I think it would be sane to have merging be enabled by default, as there's very little risk to doing so.

2018-01-30 17:00 UTC, shadowhand commented on src/MergedConfigCollection.php
> +        return $found !== null ? $found : $default;
Might be time to consider a PHP 7.1 baseline requirement. 🤔 This could become:

```php
return $found ?? $default;
```

2018-01-30 21:43 UTC, kegi commented
Applied your recommendations.
Travis is failing because of php 5.6 tests. ;)

2018-02-01 14:49 UTC, shadowhand approved these changes

2018-02-01 14:49 UTC, shadowhand commented on .travis.yml
> +    - php: 7.0
Ah, I didn't mean to switch to PHP 7 as part of this PR... but I guess that's okay. Change is going to require a major version bump anyways.

2018-02-01 14:53 UTC, merged

2018-02-01 14:53 UTC, shadowhand commented
Thanks, merged. Going to do some PHP 7 cleanup and then release version 2.0.0.